const COUNTRIES = [
  { cn: '阿富汗', py: 'Āfùhàn', en: 'Afghanistan', iso: 'AFG', lat: 33.93, lng: 67.71, continent: 'Asia' },
  { cn: '阿尔巴尼亚', py: 'Āěrbāníyà', en: 'Albania', iso: 'ALB', lat: 41.15, lng: 20.17, continent: 'Europe' },
  { cn: '阿尔及利亚', py: 'Āěrjílìyà', en: 'Algeria', iso: 'DZA', lat: 28.03, lng: 1.65, continent: 'Africa' },
  { cn: '安道尔', py: 'Āndào\'ěr', en: 'Andorra', iso: 'AND', lat: 42.54, lng: 1.60, continent: 'Europe' },
  { cn: '安哥拉', py: 'Āngēlā', en: 'Angola', iso: 'AGO', lat: -11.20, lng: 17.87, continent: 'Africa' },
  { cn: '安提瓜和巴布达', py: 'Āntíguā hé Bābùdá', en: 'Antigua and Barbuda', iso: 'ATG', lat: 17.06, lng: -61.80, continent: 'North America' },
  { cn: '阿根廷', py: 'Āgēntíng', en: 'Argentina', iso: 'ARG', lat: -38.41, lng: -63.61, continent: 'South America' },
  { cn: '亚美尼亚', py: 'Yàměiníyà', en: 'Armenia', iso: 'ARM', lat: 40.07, lng: 45.04, continent: 'Asia' },
  { cn: '澳大利亚', py: 'Àodàlìyà', en: 'Australia', iso: 'AUS', lat: -25.27, lng: 133.77, continent: 'Oceania' },
  { cn: '奥地利', py: 'Àodìlì', en: 'Austria', iso: 'AUT', lat: 47.52, lng: 14.55, continent: 'Europe' },
  { cn: '阿塞拜疆', py: 'Āsèbàijiāng', en: 'Azerbaijan', iso: 'AZE', lat: 40.14, lng: 47.57, continent: 'Asia' },
  { cn: '巴哈马', py: 'Bāhāmǎ', en: 'Bahamas', iso: 'BHS', lat: 25.03, lng: -77.40, continent: 'North America' },
  { cn: '巴林', py: 'Bālín', en: 'Bahrain', iso: 'BHR', lat: 26.02, lng: 50.55, continent: 'Asia' },
  { cn: '孟加拉国', py: 'Mèngjiālāguó', en: 'Bangladesh', iso: 'BGD', lat: 23.68, lng: 90.35, continent: 'Asia' },
  { cn: '巴巴多斯', py: 'Bābāduōsī', en: 'Barbados', iso: 'BRB', lat: 13.19, lng: -59.54, continent: 'North America' },
  { cn: '白俄罗斯', py: 'Bái\'éluósī', en: 'Belarus', iso: 'BLR', lat: 53.70, lng: 27.95, continent: 'Europe' },
  { cn: '比利时', py: 'Bǐlìshí', en: 'Belgium', iso: 'BEL', lat: 50.50, lng: 4.47, continent: 'Europe' },
  { cn: '伯利兹', py: 'Bólìzī', en: 'Belize', iso: 'BLZ', lat: 17.19, lng: -88.49, continent: 'North America' },
  { cn: '贝宁', py: 'Bèiníng', en: 'Benin', iso: 'BEN', lat: 9.31, lng: 2.32, continent: 'Africa' },
  { cn: '不丹', py: 'Bùdān', en: 'Bhutan', iso: 'BTN', lat: 27.51, lng: 90.43, continent: 'Asia' },
  { cn: '玻利维亚', py: 'Bōlìwéiyà', en: 'Bolivia', iso: 'BOL', lat: -16.29, lng: -63.59, continent: 'South America' },
  { cn: '波斯尼亚和黑塞哥维那', py: 'Bōsīníyà hé Hēisāigēwéinà', en: 'Bosnia and Herzegovina', iso: 'BIH', lat: 43.92, lng: 17.68, continent: 'Europe' },
  { cn: '博茨瓦纳', py: 'Bócíwǎnà', en: 'Botswana', iso: 'BWA', lat: -22.33, lng: 24.68, continent: 'Africa' },
  { cn: '巴西', py: 'Bāxī', en: 'Brazil', iso: 'BRA', lat: -14.23, lng: -51.92, continent: 'South America' },
  { cn: '文莱', py: 'Wénlái', en: 'Brunei', iso: 'BRN', lat: 4.53, lng: 114.73, continent: 'Asia' },
  { cn: '保加利亚', py: 'Bǎojiālìyà', en: 'Bulgaria', iso: 'BGR', lat: 42.73, lng: 25.48, continent: 'Europe' },
  { cn: '布基纳法索', py: 'Bùjīnàfǎsuǒ', en: 'Burkina Faso', iso: 'BFA', lat: 12.36, lng: -1.53, continent: 'Africa' },
  { cn: '布隆迪', py: 'Bùlóngdí', en: 'Burundi', iso: 'BDI', lat: -3.37, lng: 29.91, continent: 'Africa' },
  { cn: '佛得角', py: 'Fódékǎo', en: 'Cabo Verde', iso: 'CPV', lat: 16.00, lng: -24.01, continent: 'Africa' },
  { cn: '柬埔寨', py: 'Jiǎnpǔzhài', en: 'Cambodia', iso: 'KHM', lat: 12.57, lng: 104.99, continent: 'Asia' },
  { cn: '喀麦隆', py: 'Kāmàilóng', en: 'Cameroon', iso: 'CMR', lat: 7.37, lng: 12.35, continent: 'Africa' },
  { cn: '加拿大', py: 'Jiānádà', en: 'Canada', iso: 'CAN', lat: 56.13, lng: -106.34, continent: 'North America' },
  { cn: '中非共和国', py: 'Zhōngfēi Gònghéguó', en: 'Central African Republic', iso: 'CAF', lat: 6.61, lng: 20.94, continent: 'Africa' },
  { cn: '乍得', py: 'Zhàdé', en: 'Chad', iso: 'TCD', lat: 15.45, lng: 18.73, continent: 'Africa' },
  { cn: '智利', py: 'Zhìlì', en: 'Chile', iso: 'CHL', lat: -35.67, lng: -71.54, continent: 'South America' },
  { cn: '中国', py: 'Zhōngguó', en: 'China', iso: 'CHN', lat: 35.86, lng: 104.19, continent: 'Asia' },
  { cn: '哥伦比亚', py: 'Gēlúnbǐyà', en: 'Colombia', iso: 'COL', lat: 4.57, lng: -74.30, continent: 'South America' },
  { cn: '科摩罗', py: 'Kēmóluō', en: 'Comoros', iso: 'COM', lat: -11.64, lng: 43.33, continent: 'Africa' },
  { cn: '刚果共和国', py: 'Gānggǒ Gònghéguó', en: 'Congo', iso: 'COG', lat: -0.23, lng: 15.83, continent: 'Africa' },
  { cn: '刚果民主共和国', py: 'Gānggǒ Mínzhǔ Gònghéguó', en: 'DR Congo', iso: 'COD', lat: -4.03, lng: 21.75, continent: 'Africa' },
  { cn: '哥斯达黎加', py: 'Gēsīdálíjiā', en: 'Costa Rica', iso: 'CRI', lat: 9.75, lng: -83.75, continent: 'North America' },
  { cn: '科特迪瓦', py: 'Kētèdíwǎ', en: 'Côte d\'Ivoire', iso: 'CIV', lat: 7.54, lng: -5.55, continent: 'Africa' },
  { cn: '克罗地亚', py: 'Kèluódìyà', en: 'Croatia', iso: 'HRV', lat: 45.10, lng: 15.20, continent: 'Europe' },
  { cn: '古巴', py: 'Gǔbā', en: 'Cuba', iso: 'CUB', lat: 21.52, lng: -77.78, continent: 'North America' },
  { cn: '塞浦路斯', py: 'Sāipǔlùsī', en: 'Cyprus', iso: 'CYP', lat: 35.13, lng: 33.43, continent: 'Asia' },
  { cn: '捷克', py: 'Jiékè', en: 'Czechia', iso: 'CZE', lat: 49.82, lng: 15.47, continent: 'Europe' },
  { cn: '丹麦', py: 'Dānmài', en: 'Denmark', iso: 'DNK', lat: 56.26, lng: 9.50, continent: 'Europe' },
  { cn: '吉布提', py: 'Jíbùtí', en: 'Djibouti', iso: 'DJI', lat: 11.83, lng: 42.59, continent: 'Africa' },
  { cn: '多米尼加', py: 'Duōmǐníjiā', en: 'Dominica', iso: 'DMA', lat: 15.41, lng: -61.37, continent: 'North America' },
  { cn: '多米尼加共和国', py: 'Duōmǐníjiā Gònghéguó', en: 'Dominican Republic', iso: 'DOM', lat: 18.74, lng: -70.16, continent: 'North America' },
  { cn: '厄瓜多尔', py: 'Èguāduō\'ěr', en: 'Ecuador', iso: 'ECU', lat: -1.83, lng: -78.18, continent: 'South America' },
  { cn: '埃及', py: 'Āijí', en: 'Egypt', iso: 'EGY', lat: 26.82, lng: 30.80, continent: 'Africa' },
  { cn: '萨尔瓦多', py: 'Sà\'ěrwǎduō', en: 'El Salvador', iso: 'SLV', lat: 13.79, lng: -88.90, continent: 'North America' },
  { cn: '赤道几内亚', py: 'Chìdào Jǐnèiyà', en: 'Equatorial Guinea', iso: 'GNQ', lat: 1.65, lng: 10.27, continent: 'Africa' },
  { cn: '厄立特里亚', py: 'Èlìtèlǐyà', en: 'Eritrea', iso: 'ERI', lat: 15.17, lng: 39.78, continent: 'Africa' },
  { cn: '爱沙尼亚', py: 'Àishāníyà', en: 'Estonia', iso: 'EST', lat: 58.59, lng: 25.01, continent: 'Europe' },
  { cn: '斯威士兰', py: 'Sīwēishìlán', en: 'Eswatini', iso: 'SWZ', lat: -26.52, lng: 31.47, continent: 'Africa' },
  { cn: '埃塞俄比亚', py: 'Āisài\'ébǐyà', en: 'Ethiopia', iso: 'ETH', lat: 9.14, lng: 40.49, continent: 'Africa' },
  { cn: '斐济', py: 'Fèijì', en: 'Fiji', iso: 'FJI', lat: -16.58, lng: 179.41, continent: 'Oceania' },
  { cn: '芬兰', py: 'Fēnlán', en: 'Finland', iso: 'FIN', lat: 61.92, lng: 25.75, continent: 'Europe' },
  { cn: '法国', py: 'Fǎguó', en: 'France', iso: 'FRA', lat: 46.22, lng: 2.21, continent: 'Europe' },
  { cn: '加蓬', py: 'Jiābèng', en: 'Gabon', iso: 'GAB', lat: -0.80, lng: 11.61, continent: 'Africa' },
  { cn: '冈比亚', py: 'Gǎngbǐyà', en: 'Gambia', iso: 'GMB', lat: 13.44, lng: -15.31, continent: 'Africa' },
  { cn: '格鲁吉亚', py: 'Gélǔjíyà', en: 'Georgia', iso: 'GEO', lat: 42.31, lng: 43.36, continent: 'Asia' },
  { cn: '德国', py: 'Déguó', en: 'Germany', iso: 'DEU', lat: 51.16, lng: 10.45, continent: 'Europe' },
  { cn: '加纳', py: 'Jiānà', en: 'Ghana', iso: 'GHA', lat: 7.95, lng: -1.02, continent: 'Africa' },
  { cn: '希腊', py: 'Xīlà', en: 'Greece', iso: 'GRC', lat: 39.07, lng: 21.82, continent: 'Europe' },
  { cn: '格林纳达', py: 'Gélínnádá', en: 'Grenada', iso: 'GRD', lat: 12.11, lng: -61.67, continent: 'North America' },
  { cn: '危地马拉', py: 'Wēidìmǎlā', en: 'Guatemala', iso: 'GTM', lat: 15.78, lng: -90.23, continent: 'North America' },
  { cn: '几内亚', py: 'Jǐnèiyà', en: 'Guinea', iso: 'GIN', lat: 9.95, lng: -11.24, continent: 'Africa' },
  { cn: '几内亚比绍', py: 'Jǐnèiyà Bǐshào', en: 'Guinea-Bissau', iso: 'GNB', lat: 11.80, lng: -15.18, continent: 'Africa' },
  { cn: '圭亚那', py: 'Guīyànà', en: 'Guyana', iso: 'GUY', lat: 4.86, lng: -58.93, continent: 'South America' },
  { cn: '海地', py: 'Hǎidì', en: 'Haiti', iso: 'HTI', lat: 18.97, lng: -72.28, continent: 'North America' },
  { cn: '洪都拉斯', py: 'Hóngdūlāsī', en: 'Honduras', iso: 'HND', lat: 15.19, lng: -86.24, continent: 'North America' },
  { cn: '匈牙利', py: 'Xiōngyálì', en: 'Hungary', iso: 'HUN', lat: 47.16, lng: 19.50, continent: 'Europe' },
  { cn: '冰岛', py: 'Bīngdǎo', en: 'Iceland', iso: 'ISL', lat: 64.96, lng: -19.02, continent: 'Europe' },
  { cn: '印度', py: 'Yìndù', en: 'India', iso: 'IND', lat: 20.59, lng: 78.96, continent: 'Asia' },
  { cn: '印度尼西亚', py: 'Yìndùníxīyà', en: 'Indonesia', iso: 'IDN', lat: -0.79, lng: 113.92, continent: 'Asia' },
  { cn: '伊朗', py: 'Yīlǎng', en: 'Iran', iso: 'IRN', lat: 32.42, lng: 53.68, continent: 'Asia' },
  { cn: '伊拉克', py: 'Yīlākè', en: 'Iraq', iso: 'IRQ', lat: 33.22, lng: 43.68, continent: 'Asia' },
  { cn: '爱尔兰', py: 'Ài\'ěrlán', en: 'Ireland', iso: 'IRL', lat: 53.41, lng: -8.24, continent: 'Europe' },
  { cn: '以色列', py: 'Yǐsèliè', en: 'Israel', iso: 'ISR', lat: 31.04, lng: 34.85, continent: 'Asia' },
  { cn: '意大利', py: 'Yìdàlì', en: 'Italy', iso: 'ITA', lat: 41.87, lng: 12.56, continent: 'Europe' },
  { cn: '牙买加', py: 'Yámǎijiā', en: 'Jamaica', iso: 'JAM', lat: 18.10, lng: -77.30, continent: 'North America' },
  { cn: '日本', py: 'Rìběn', en: 'Japan', iso: 'JPN', lat: 36.20, lng: 138.25, continent: 'Asia' },
  { cn: '约旦', py: 'Yuēdàn', en: 'Jordan', iso: 'JOR', lat: 30.59, lng: 36.24, continent: 'Asia' },
  { cn: '哈萨克斯坦', py: 'Hāsàkèsītǎn', en: 'Kazakhstan', iso: 'KAZ', lat: 48.01, lng: 66.92, continent: 'Asia' },
  { cn: '肯尼亚', py: 'Kěnníyà', en: 'Kenya', iso: 'KEN', lat: -0.02, lng: 37.91, continent: 'Africa' },
  { cn: '基里巴斯', py: 'Jīlǐbāsī', en: 'Kiribati', iso: 'KIR', lat: -3.37, lng: -168.73, continent: 'Oceania' },
  { cn: '朝鲜', py: 'Cháoxiǎn', en: 'North Korea', iso: 'PRK', lat: 40.34, lng: 127.51, continent: 'Asia' },
  { cn: '韩国', py: 'Hánguó', en: 'South Korea', iso: 'KOR', lat: 35.90, lng: 127.76, continent: 'Asia' },
  { cn: '科威特', py: 'Kēwēitè', en: 'Kuwait', iso: 'KWT', lat: 29.31, lng: 47.48, continent: 'Asia' },
  { cn: '吉尔吉斯斯坦', py: 'Jí\'ěrjísīsītǎn', en: 'Kyrgyzstan', iso: 'KGZ', lat: 41.20, lng: 74.76, continent: 'Asia' },
  { cn: '老挝', py: 'Lǎowō', en: 'Laos', iso: 'LAO', lat: 19.85, lng: 102.49, continent: 'Asia' },
  { cn: '拉脱维亚', py: 'Lātuōwéiyà', en: 'Latvia', iso: 'LVA', lat: 56.88, lng: 24.60, continent: 'Europe' },
  { cn: '黎巴嫩', py: 'Líbānèn', en: 'Lebanon', iso: 'LBN', lat: 33.85, lng: 35.86, continent: 'Asia' },
  { cn: '莱索托', py: 'Láisuǒtuō', en: 'Lesotho', iso: 'LSO', lat: -29.61, lng: 28.23, continent: 'Africa' },
  { cn: '利比里亚', py: 'Lìbǐlìyà', en: 'Liberia', iso: 'LBR', lat: 6.43, lng: -9.43, continent: 'Africa' },
  { cn: '利比亚', py: 'Lìbǐyà', en: 'Libya', iso: 'LBY', lat: 26.33, lng: 17.22, continent: 'Africa' },
  { cn: '列支敦士登', py: 'Lièzhīdūnshìdēng', en: 'Liechtenstein', iso: 'LIE', lat: 47.14, lng: 9.55, continent: 'Europe' },
  { cn: '立陶宛', py: 'Lìtáowǎn', en: 'Lithuania', iso: 'LTU', lat: 55.17, lng: 23.88, continent: 'Europe' },
  { cn: '卢森堡', py: 'Lúsēnbǎo', en: 'Luxembourg', iso: 'LUX', lat: 49.81, lng: 6.13, continent: 'Europe' },
  { cn: '马达加斯加', py: 'Mǎdájiāsījiā', en: 'Madagascar', iso: 'MDG', lat: -18.77, lng: 46.87, continent: 'Africa' },
  { cn: '马拉维', py: 'Mǎlāwéi', en: 'Malawi', iso: 'MWI', lat: -13.25, lng: 34.30, continent: 'Africa' },
  { cn: '马来西亚', py: 'Mǎláixīyà', en: 'Malaysia', iso: 'MYS', lat: 4.21, lng: 108.96, continent: 'Asia' },
  { cn: '马尔代夫', py: 'Mǎ\'ěrdàifū', en: 'Maldives', iso: 'MDV', lat: 3.20, lng: 73.22, continent: 'Asia' },
  { cn: '马里', py: 'Mǎlǐ', en: 'Mali', iso: 'MLI', lat: 17.57, lng: -3.99, continent: 'Africa' },
  { cn: '马耳他', py: 'Mǎ\'ěrtā', en: 'Malta', iso: 'MLT', lat: 35.94, lng: 14.37, continent: 'Europe' },
  { cn: '马绍尔群岛', py: 'Mǎshào\'ěr Qúndǎo', en: 'Marshall Islands', iso: 'MHL', lat: 7.13, lng: 171.18, continent: 'Oceania' },
  { cn: '毛里塔尼亚', py: 'Máolǐtǎníyà', en: 'Mauritania', iso: 'MRT', lat: 21.00, lng: -10.94, continent: 'Africa' },
  { cn: '毛里求斯', py: 'Máolǐqiúsī', en: 'Mauritius', iso: 'MUS', lat: -20.35, lng: 57.55, continent: 'Africa' },
  { cn: '墨西哥', py: 'Mòxīgē', en: 'Mexico', iso: 'MEX', lat: 23.63, lng: -102.55, continent: 'North America' },
  { cn: '密克罗尼西亚', py: 'Mìkèluóníxīyà', en: 'Micronesia', iso: 'FSM', lat: 7.42, lng: 150.55, continent: 'Oceania' },
  { cn: '摩尔多瓦', py: 'Mó\'ěrduōwǎ', en: 'Moldova', iso: 'MDA', lat: 47.41, lng: 28.37, continent: 'Europe' },
  { cn: '摩纳哥', py: 'Mónàgē', en: 'Monaco', iso: 'MCO', lat: 43.73, lng: 7.40, continent: 'Europe' },
  { cn: '蒙古', py: 'Měnggǔ', en: 'Mongolia', iso: 'MNG', lat: 46.86, lng: 103.84, continent: 'Asia' },
  { cn: '黑山', py: 'Hēishān', en: 'Montenegro', iso: 'MNE', lat: 42.71, lng: 19.37, continent: 'Europe' },
  { cn: '摩洛哥', py: 'Móluògē', en: 'Morocco', iso: 'MAR', lat: 31.79, lng: -7.09, continent: 'Africa' },
  { cn: '莫桑比克', py: 'Mòsāngbǐkè', en: 'Mozambique', iso: 'MOZ', lat: -18.66, lng: 35.52, continent: 'Africa' },
  { cn: '缅甸', py: 'Miǎndiàn', en: 'Myanmar', iso: 'MMR', lat: 21.91, lng: 95.96, continent: 'Asia' },
  { cn: '纳米比亚', py: 'Nàmǐbǐyà', en: 'Namibia', iso: 'NAM', lat: -22.96, lng: 18.49, continent: 'Africa' },
  { cn: '瑙鲁', py: 'Nǎolǔ', en: 'Nauru', iso: 'NRU', lat: -0.52, lng: 166.93, continent: 'Oceania' },
  { cn: '尼泊尔', py: 'Níbó\'ěr', en: 'Nepal', iso: 'NPL', lat: 28.39, lng: 84.12, continent: 'Asia' },
  { cn: '荷兰', py: 'Hélán', en: 'Netherlands', iso: 'NLD', lat: 52.13, lng: 5.29, continent: 'Europe' },
  { cn: '新西兰', py: 'Xīnxīlán', en: 'New Zealand', iso: 'NZL', lat: -40.90, lng: 174.89, continent: 'Oceania' },
  { cn: '尼加拉瓜', py: 'Níjiālāguā', en: 'Nicaragua', iso: 'NIC', lat: 12.86, lng: -85.21, continent: 'North America' },
  { cn: '尼日尔', py: 'Nírì\'ěr', en: 'Niger', iso: 'NER', lat: 17.60, lng: 8.08, continent: 'Africa' },
  { cn: '尼日利亚', py: 'Nírìlìyà', en: 'Nigeria', iso: 'NGA', lat: 9.08, lng: 8.67, continent: 'Africa' },
  { cn: '北马其顿', py: 'Běi Mǎqídùn', en: 'North Macedonia', iso: 'MKD', lat: 41.61, lng: 21.74, continent: 'Europe' },
  { cn: '挪威', py: 'Nuówēi', en: 'Norway', iso: 'NOR', lat: 60.47, lng: 8.46, continent: 'Europe' },
  { cn: '阿曼', py: 'Āmàn', en: 'Oman', iso: 'OMN', lat: 21.51, lng: 55.92, continent: 'Asia' },
  { cn: '巴基斯坦', py: 'Bājīsītǎn', en: 'Pakistan', iso: 'PAK', lat: 30.37, lng: 69.34, continent: 'Asia' },
  { cn: '帕劳', py: 'Pàláo', en: 'Palau', iso: 'PLW', lat: 7.51, lng: 134.58, continent: 'Oceania' },
  { cn: '巴拿马', py: 'Bānámǎ', en: 'Panama', iso: 'PAN', lat: 8.54, lng: -80.78, continent: 'North America' },
  { cn: '巴布亚新几内亚', py: 'Bābùyà Xīnjǐnèiyà', en: 'Papua New Guinea', iso: 'PNG', lat: -6.31, lng: 143.95, continent: 'Oceania' },
  { cn: '巴拉圭', py: 'Bālāguī', en: 'Paraguay', iso: 'PRY', lat: -23.44, lng: -58.44, continent: 'South America' },
  { cn: '秘鲁', py: 'Bìlǔ', en: 'Peru', iso: 'PER', lat: -9.19, lng: -75.01, continent: 'South America' },
  { cn: '菲律宾', py: 'Fēilǜbīn', en: 'Philippines', iso: 'PHL', lat: 12.88, lng: 121.77, continent: 'Asia' },
  { cn: '波兰', py: 'Bōlán', en: 'Poland', iso: 'POL', lat: 51.91, lng: 19.14, continent: 'Europe' },
  { cn: '葡萄牙', py: 'Pútáoyá', en: 'Portugal', iso: 'PRT', lat: 39.40, lng: -8.22, continent: 'Europe' },
  { cn: '卡塔尔', py: 'Kǎtǎ\'ěr', en: 'Qatar', iso: 'QAT', lat: 25.35, lng: 51.18, continent: 'Asia' },
  { cn: '罗马尼亚', py: 'Luómǎníyà', en: 'Romania', iso: 'ROU', lat: 45.94, lng: 24.97, continent: 'Europe' },
  { cn: '俄罗斯', py: 'Éluósī', en: 'Russia', iso: 'RUS', lat: 61.52, lng: 105.31, continent: 'Europe' },
  { cn: '卢旺达', py: 'Lúwàngdá', en: 'Rwanda', iso: 'RWA', lat: -1.94, lng: 29.87, continent: 'Africa' },
  { cn: '圣基茨和尼维斯', py: 'Shèngjījí hé Níwéisī', en: 'Saint Kitts and Nevis', iso: 'KNA', lat: 17.36, lng: -62.78, continent: 'North America' },
  { cn: '圣卢西亚', py: 'Shènglúxīyà', en: 'Saint Lucia', iso: 'LCA', lat: 13.91, lng: -60.97, continent: 'North America' },
  { cn: '圣文森特和格林纳丁斯', py: 'Shèngwénsēntè hé Gélínnádīngsī', en: 'Saint Vincent and the Grenadines', iso: 'VCT', lat: 13.25, lng: -61.20, continent: 'North America' },
  { cn: '萨摩亚', py: 'Sàmóyà', en: 'Samoa', iso: 'WSM', lat: -13.76, lng: -172.10, continent: 'Oceania' },
  { cn: '圣马力诺', py: 'Shèngmǎlìnuò', en: 'San Marino', iso: 'SMR', lat: 43.94, lng: 12.46, continent: 'Europe' },
  { cn: '圣多美和普林西比', py: 'Shèngduōměi hé Pǔlínxībǐ', en: 'Sao Tome and Principe', iso: 'STP', lat: 0.19, lng: 6.61, continent: 'Africa' },
  { cn: '沙特阿拉伯', py: 'Shātè Ālābó', en: 'Saudi Arabia', iso: 'SAU', lat: 23.88, lng: 45.07, continent: 'Asia' },
  { cn: '塞内加尔', py: 'Sāinèijiā\'ěr', en: 'Senegal', iso: 'SEN', lat: 14.50, lng: -14.45, continent: 'Africa' },
  { cn: '塞尔维亚', py: 'Sāi\'ěrwéiyà', en: 'Serbia', iso: 'SRB', lat: 44.02, lng: 21.00, continent: 'Europe' },
  { cn: '塞舌尔', py: 'Sāishé\'ěr', en: 'Seychelles', iso: 'SYC', lat: -4.68, lng: 55.49, continent: 'Africa' },
  { cn: '塞拉利昂', py: 'Sāilālì\'áng', en: 'Sierra Leone', iso: 'SLE', lat: 8.46, lng: -11.78, continent: 'Africa' },
  { cn: '新加坡', py: 'Xīnjiāpō', en: 'Singapore', iso: 'SGP', lat: 1.35, lng: 103.82, continent: 'Asia' },
  { cn: '斯洛伐克', py: 'Sīluòfákè', en: 'Slovakia', iso: 'SVK', lat: 48.67, lng: 19.70, continent: 'Europe' },
  { cn: '斯洛文尼亚', py: 'Sīluòwénníyà', en: 'Slovenia', iso: 'SVN', lat: 46.15, lng: 14.99, continent: 'Europe' },
  { cn: '所罗门群岛', py: 'Suǒluómén Qúndǎo', en: 'Solomon Islands', iso: 'SLB', lat: -9.64, lng: 160.15, continent: 'Oceania' },
  { cn: '索马里', py: 'Suǒmǎlǐ', en: 'Somalia', iso: 'SOM', lat: 5.15, lng: 46.20, continent: 'Africa' },
  { cn: '南非', py: 'Nán Fēi', en: 'South Africa', iso: 'ZAF', lat: -30.55, lng: 22.93, continent: 'Africa' },
  { cn: '南苏丹', py: 'Nán Sūdān', en: 'South Sudan', iso: 'SSD', lat: 6.87, lng: 31.31, continent: 'Africa' },
  { cn: '西班牙', py: 'Xībānyá', en: 'Spain', iso: 'ESP', lat: 40.46, lng: -3.74, continent: 'Europe' },
  { cn: '斯里兰卡', py: 'Sīlǐlánkǎ', en: 'Sri Lanka', iso: 'LKA', lat: 7.87, lng: 80.77, continent: 'Asia' },
  { cn: '苏丹', py: 'Sūdān', en: 'Sudan', iso: 'SDN', lat: 12.86, lng: 30.22, continent: 'Africa' },
  { cn: '苏里南', py: 'Sūlǐnán', en: 'Suriname', iso: 'SUR', lat: 3.92, lng: -56.02, continent: 'South America' },
  { cn: '瑞典', py: 'Ruìdiǎn', en: 'Sweden', iso: 'SWE', lat: 60.12, lng: 18.64, continent: 'Europe' },
  { cn: '瑞士', py: 'Ruìshì', en: 'Switzerland', iso: 'CHE', lat: 46.82, lng: 8.23, continent: 'Europe' },
  { cn: '叙利亚', py: 'Xùlìyà', en: 'Syria', iso: 'SYR', lat: 34.80, lng: 38.99, continent: 'Asia' },
  { cn: '塔吉克斯坦', py: 'Tǎjíkèsītǎn', en: 'Tajikistan', iso: 'TJK', lat: 38.86, lng: 71.27, continent: 'Asia' },
  { cn: '坦桑尼亚', py: 'Tǎnsāngníyà', en: 'Tanzania', iso: 'TZA', lat: -6.37, lng: 34.89, continent: 'Africa' },
  { cn: '泰国', py: 'Tàiguó', en: 'Thailand', iso: 'THA', lat: 15.87, lng: 100.99, continent: 'Asia' },
  { cn: '东帝汶', py: 'Dōng Dìwèn', en: 'Timor-Leste', iso: 'TLS', lat: -8.87, lng: 125.73, continent: 'Asia' },
  { cn: '多哥', py: 'Duōgē', en: 'Togo', iso: 'TGO', lat: 8.61, lng: 0.82, continent: 'Africa' },
  { cn: '汤加', py: 'Tāngjiā', en: 'Tonga', iso: 'TON', lat: -21.18, lng: -175.20, continent: 'Oceania' },
  { cn: '特立尼达和多巴哥', py: 'Tèlìnídá hé Duōbāgē', en: 'Trinidad and Tobago', iso: 'TTO', lat: 10.69, lng: -61.22, continent: 'North America' },
  { cn: '突尼斯', py: 'Tūnísi', en: 'Tunisia', iso: 'TUN', lat: 33.89, lng: 9.54, continent: 'Africa' },
  { cn: '土耳其', py: 'Tǔ\'ěrqí', en: 'Turkey', iso: 'TUR', lat: 38.96, lng: 35.24, continent: 'Asia' },
  { cn: '土库曼斯坦', py: 'Tǔkùmànsītǎn', en: 'Turkmenistan', iso: 'TKM', lat: 38.97, lng: 59.56, continent: 'Asia' },
  { cn: '图瓦卢', py: 'Túwǎlú', en: 'Tuvalu', iso: 'TUV', lat: -7.11, lng: 177.64, continent: 'Oceania' },
  { cn: '乌干达', py: 'Wūgāndá', en: 'Uganda', iso: 'UGA', lat: 1.37, lng: 32.29, continent: 'Africa' },
  { cn: '乌克兰', py: 'Wūkèlán', en: 'Ukraine', iso: 'UKR', lat: 48.38, lng: 31.17, continent: 'Europe' },
  { cn: '阿联酋', py: 'Āliánqiú', en: 'United Arab Emirates', iso: 'ARE', lat: 23.42, lng: 53.85, continent: 'Asia' },
  { cn: '英国', py: 'Yīngguó', en: 'United Kingdom', iso: 'GBR', lat: 55.37, lng: -3.43, continent: 'Europe' },
  { cn: '美国', py: 'Měiguó', en: 'United States', iso: 'USA', lat: 37.09, lng: -95.71, continent: 'North America' },
  { cn: '乌拉圭', py: 'Wūlāguī', en: 'Uruguay', iso: 'URY', lat: -32.52, lng: -55.76, continent: 'South America' },
  { cn: '乌兹别克斯坦', py: 'Wūzībiékèsītǎn', en: 'Uzbekistan', iso: 'UZB', lat: 41.37, lng: 64.58, continent: 'Asia' },
  { cn: '瓦努阿图', py: 'Wǎnú\'ātú', en: 'Vanuatu', iso: 'VUT', lat: -15.38, lng: 166.96, continent: 'Oceania' },
  { cn: '委内瑞拉', py: 'Wěinèiruìlā', en: 'Venezuela', iso: 'VEN', lat: 6.42, lng: -66.59, continent: 'South America' },
  { cn: '越南', py: 'Yuènán', en: 'Vietnam', iso: 'VNM', lat: 14.05, lng: 108.27, continent: 'Asia' },
  { cn: '也门', py: 'Yěmén', en: 'Yemen', iso: 'YEM', lat: 15.55, lng: 48.52, continent: 'Asia' },
  { cn: '赞比亚', py: 'Zànbǐyà', en: 'Zambia', iso: 'ZMB', lat: -13.13, lng: 27.85, continent: 'Africa' },
  { cn: '津巴布韦', py: 'Jīnbābùwéi', en: 'Zimbabwe', iso: 'ZWE', lat: -19.01, lng: 29.15, continent: 'Africa' },
];
